### ISSUE TITLE
Command name too long on Linux

### ISSUE THREAD

**Issue by bobsaintcool** [raoulh/moolticute_ssh-agent#2]
As stated into [prctl(2)](http://man7.org/linux/man-pages/man2/prctl.2.html) the command name of a process could be up to 16 bytes (or silently truncated). With a command name like moolticute_ssh-agent we are above the limit resulting on different way of interactive with the created processes.
Maybe we can consider changing the name of the executable for something smaller (like mc_ssh-agent) ?

I have no idea if it will have some influence on other platform than Linux

**Comment by bobsaintcool** [comment]
After discuss, this seems not very important we will see if someone get more in trouble later.

**Comment by NicoHood** [comment]
I also think that the name itself is quite ugly. So moolticute-agent or mc-ssh-agent could be better. At least I would not use underscore combined with hyphen.
